// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqclbakmgmixymjhewzh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxY2xiYWttZ21peHltamhld3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzMwNjMsImV4cCI6MjA2OTY0OTA2M30.SVsn8DDdYbL4Ht2mHs-nm1H4Atm9l4sCGRa2T0vsmao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});